// Generated by CoffeeScript 1.3.3
(function() {
  var displayRecentTracks, getArtist, getRecentTracks, stepArtists;

  $(function() {
    return getRecentTracks(displayRecentTracks);
  });

  displayRecentTracks = function(tracks) {
    var area, artists;
    area = $('#recent-music');
    artists = {};
    if (tracks.track.length) {
      return stepArtists(0, tracks, artists, function() {
        var artist, name, _results;
        _results = [];
        for (name in artists) {
          artist = artists[name];
          area.find('h3').show();
          _results.push(area.append("<a href='spotify:search:" + artist.name.replace(/\s/g, '+') + "'><img src='" + artist.image[2]['#text'] + "'/></a>"));
        }
        return _results;
      });
    }
  };

  stepArtists = function(index, tracks, artists, cb) {
    if (index < tracks.track.length) {
      return getArtist(tracks.track[index].artist['#text'], function(data) {
        if (artists[tracks.track[index].artist['#text']] === void 0) {
          artists[tracks.track[index].artist['#text']] = data;
        }
        return stepArtists(++index, tracks, artists, cb);
      });
    } else {
      return cb();
    }
  };

  getArtist = function(id, cb) {
    return $.getJSON('http://ws.audioscrobbler.com/2.0/?method=artist.getinfo&artist=' + id + '&api_key=1a7c2b9bdb474400ca73abd6002471cf&format=json', function(d) {
      return cb(d.artist);
    });
  };

  getRecentTracks = function(cb) {
    return $.getJSON('http://ws.audioscrobbler.com/2.0/?method=user.getrecenttracks&user=samccone&api_key=1a7c2b9bdb474400ca73abd6002471cf&limit=90&format=json', function(d) {
      return cb(d.recenttracks);
    });
  };

}).call(this);
